import Foundation

public enum GBNFCompilerError: Error, Equatable, Sendable {
    case emptyCatalog
    case duplicateToolName(String)
    case toolWithoutArguments(String)
    case duplicateArgumentName(tool: String, argument: String)
}

/// Compiles a tool catalog into a llama.cpp-compatible GBNF grammar.
///
/// What a grammar can do is bound the *shape* of the output: one call, a known
/// tool name, known argument keys, required keys present, values that are
/// strings or JSON booleans. What it cannot do is decide whether the call is
/// correct — `start_date` is a string to the sampler whether it holds an
/// ISO-8601 timestamp or the word "tomorrow", and no context-free rule can say
/// that an end date must fall after a start date. Structural validity is not
/// semantic correctness; that judgement lives in `ToolCallValidator`.
public enum GBNFCompiler {

    /// Deterministic: the same catalog always yields byte-identical output, so a
    /// grammar can be diffed, cached, or checked into a test fixture.
    public static func compile(_ tools: [ToolDefinition]) throws -> String {
        guard !tools.isEmpty else { throw GBNFCompilerError.emptyCatalog }

        var seen = Set<String>()
        for tool in tools {
            guard seen.insert(tool.name).inserted else {
                throw GBNFCompilerError.duplicateToolName(tool.name)
            }
            guard !tool.arguments.isEmpty else {
                throw GBNFCompilerError.toolWithoutArguments(tool.name)
            }
            var seenArgs = Set<String>()
            for argument in tool.arguments where !seenArgs.insert(argument.name).inserted {
                throw GBNFCompilerError.duplicateArgumentName(tool: tool.name, argument: argument.name)
            }
        }

        var lines: [String] = []
        lines.append("# Generated by ToolGuardrails.GBNFCompiler. Do not edit by hand.")
        lines.append("# Structural constraints only; semantics are checked after parsing.")
        lines.append("")
        lines.append("root ::= \"[\" ws call ws \"]\"")
        lines.append("call ::= " + tools.map { ruleName(forTool: $0.name) }.joined(separator: " | "))
        lines.append("")

        for tool in tools {
            lines.append(contentsOf: rules(for: tool))
            lines.append("")
        }

        lines.append(contentsOf: [
            #"string ::= "\"" char* "\"""#,
            #"char ::= [^"\\] | "\\" ["\\/bfnrt] | "\\u" hex hex hex hex"#,
            "hex ::= [0-9a-fA-F]",
            #"boolean ::= "true" | "false""#,
            #"ws ::= [ \t\n]*"#,
        ])

        return lines.joined(separator: "\n") + "\n"
    }

    // MARK: - Per-tool rules

    private static func rules(for tool: ToolDefinition) -> [String] {
        let base = ruleName(forTool: tool.name)
        let argsRule = "\(base)-args"

        // Required keys are emitted in catalog order and are not optional, so a
        // call missing one cannot be sampled at all. Optional keys follow, each
        // guarded by `?`. Fixing the key order is the price of expressing
        // "required" in a context-free grammar without an alternation over every
        // permutation of keys.
        var argParts: [String] = []
        for (index, argument) in tool.requiredArguments.enumerated() {
            let pair = "\(base)-\(slug(argument.name))"
            argParts.append(index == 0 ? pair : "ws \",\" ws \(pair)")
        }
        for argument in tool.optionalArguments {
            let pair = "\(base)-\(slug(argument.name))"
            let prefix = argParts.isEmpty ? "" : "ws \",\" "
            argParts.append("(\(prefix)ws \(pair))?")
        }

        var lines = [
            "\(base) ::= \"{\" ws \"\\\"name\\\"\" ws \":\" ws \"\\\"\(tool.name)\\\"\" ws \",\" ws "
                + "\"\\\"arguments\\\"\" ws \":\" ws \(argsRule) ws \"}\"",
            "\(argsRule) ::= \"{\" ws " + argParts.joined(separator: " ") + " ws \"}\"",
        ]

        for argument in tool.arguments {
            let value = argument.type == .boolean ? "boolean" : "string"
            lines.append("\(base)-\(slug(argument.name)) ::= \"\\\"\(argument.name)\\\"\" ws \":\" ws \(value)")
        }

        return lines
    }

    // MARK: - Naming

    /// GBNF rule names allow letters, digits and dashes, so underscores in tool
    /// and argument names are folded to dashes.
    private static func ruleName(forTool name: String) -> String { "tool-" + slug(name) }

    private static func slug(_ name: String) -> String {
        String(name.map { $0 == "_" ? "-" : $0 })
    }
}
